/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { MeshPhysicalMaterial } from "three"
import React from "react"
import { useGLTF } from "@react-three/drei"

export function HeartFaceEmojiModel(props) {
  const { nodes, materials } = useGLTF(
    "https://ik.imagekit.io/5xtlzx2c3y/website/art/3d/meshes/heartFaceEmoji.glb?updatedAt=1693806057989"
  )

  const heartMaterial = new MeshPhysicalMaterial({
    color: "red",
    metalness: 0.2,
    transmission: 1.2,
    roughness: 0.1,
  })

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.model_1.geometry}
        material={materials.model_1}
        position={[-0.02, 0, -0.521]}
        rotation={[Math.PI / 2, 0, -1.554]}
        scale={0.126}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.model_2.geometry}
        material={heartMaterial}
        position={[-0.02, 0, -0.521]}
        rotation={[Math.PI / 2, 0, -1.554]}
        scale={0.126}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.model_3.geometry}
        material={heartMaterial}
        position={[-0.02, 0, -0.521]}
        rotation={[Math.PI / 2, 0, -1.554]}
        scale={0.126}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.model_4.geometry}
        material={heartMaterial}
        position={[-0.02, 0, -0.521]}
        rotation={[Math.PI / 2, 0, -1.554]}
        scale={0.126}
      />
    </group>
  )
}
