/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// import { MeshPhysicalMaterial } from "three"
import React, { lazy } from "react"

import { useGLTF } from "@react-three/drei"

const MeshPhysicalMaterial = lazy(() =>
  import("three").then(module => ({ default: module.MeshPhysicalMaterial }))
)

export default function ReverseLavaLampModel(props) {
  const { nodes } = useGLTF(
    "https://ik.imagekit.io/5xtlzx2c3y/website/art/3d/meshes/reverseLavaLamp.glb?updatedAt=1704249440319"
  )
  const capMaterial = new MeshPhysicalMaterial({
    color: "#a219fc",
    metalness: 0,
    roughness: 0.2,
    transmission: 0.9,
    thickness: 2.5,
    transparent: true,
    reflectivity: 0.5,
  })

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0.geometry}
        material={
          // metal center
          new MeshPhysicalMaterial({
            color: "#8a8a8a",
            roughness: 0.4,
            transmission: 0.7,
            thickness: 0.1,
            transparent: true,
            clearcoat: 1,
            clearcoatRoughness: 1,
          })
        }
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_1.geometry}
        material={capMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_2.geometry}
        material={
          new MeshPhysicalMaterial({
            color: "#ed4107",
            metalness: 0,
            roughness: 0.5,
            emissive: "#fa053a",
            emissiveIntensity: 2,
          })
        }
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_3.geometry}
        material={capMaterial}
      />
    </group>
  )
}
