name: Cypress Tests

on:
  push:
    branches:
      - "master"

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests

      - name: Start server
        uses: ./
        with:
          working-directory: server
          build: npm run build
          start: npm run start:test
          wait-on: "http://localhost:3001"
        env:
          IMAGEKIT_PRIVATE: ${{ secrets.IMAGEKIT_PRIVATE }}
          MJ_APIKEY_PUBLIC: ${{ secrets.MJ_APIKEY_PUBLIC }}
          MJ_APIKEY_PRIVATE: ${{ secrets.MJ_APIKEY_PRIVATE }}
          REACT_APP_MONGO_PASSWORD: ${{ secrets.REACT_APP_MONGO_PASSWORD }}

      - name: Cypress run
        uses: cypress-io/github-action@v6
        timeout-minutes: 10
        with:
          record: true
          build: npm run build
          start: npm run start
          wait-on: "http://localhost:3000, http://localhost:3001"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
